language: node_js

cache: yarn

git:
    quiet: true

node_js:
    - 'lts/*'
    - 'node'

# os
dist: focal

os:
    - linux
    - osx
    - windows

osx_image: xcode12

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script: 
    - echo "Running tests against $(node -v)..."
    - yarn test