name: CI

on:
    push:
        paths-ignore:
            - "docs/**"
            - "*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "*.md"

jobs:
    lint:
        name: Lint Code
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.x
            - name: Get NPM Cache Directory
              id: npm-cache-dir
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v2.1.4
              id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.node-version }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-${{ matrix.node-version }}-node-
            - name: Install
              run: npm ci --ignore-scripts
            - name: Run ESLint
              run: npm run lint
            - name: Run Prettier
              run: npm run lint:prettier:ci
            - name: Run Lockfile Linter
              run: npx lockfile-lint --path package-lock.json --type npm --allowed-hosts npm --validate-https

    commit-lint:
        name: Lint Commit Messages
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v3.0.1
              with:
                  configFile: ./package.json

    build:
        name: Build
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: Get NPM Cache Directory
              id: npm-cache-dir
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"
            - uses: actions/cache@v2.1.4
              id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.node-version }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-${{ matrix.node-version }}-node-
            - name: Install
              run: npm ci --ignore-scripts
            - name: Run Babel
              run: npm run build

    automerge:
        name: Automatically Merge Dependabot Pull Requests
        if: github.event.pull_request.draft == false
        needs: [build, commit-lint, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v1.1.1
              if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    release:
        name: Create/Update Release Pull Request
        if: github.ref == 'refs/heads/master'
        needs: [build, commit-lint, lint]
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              id: release
              uses: GoogleCloudPlatform/release-please-action@v2.20.1
              with:
                  changelog-types: '[ { "type": "feat", "section": "Features", "hidden": false }, { "type": "fix", "section": "Bug Fixes", "hidden": false }, { "type": "build", "section": "Dependencies", "hidden": false }, { "type": "chore", "section": "Miscellaneous", "hidden": false }, { "type": "ci", "section": "Miscellaneous", "hidden": false }, { "type": "perf", "section": "Performance", "hidden": false }, { "type": "refactor", "section": "Miscellaneous", "hidden": false }, { "type": "style", "section": "Miscellaneous", "hidden": false }, { "type": "docs", "section": "Documentation", "hidden": false }]'
                  release-type: node
