name: Check Markdown for Broken Links

on:
    schedule:
        # 01:30 every day
        - cron: "30 1 * * *"
    # Allows this workflow to be run manually from the Actions tab
    workflow_dispatch:

jobs:
    link-check:
        name: Link Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.x
            - name: Run Linkinator
              run: npx linkinator *.md docs/**/*.md --skip 'https://github.com/Fdawgs/.*/issues/, https://github.com/Fdawgs/.*/commit/, https://sider.ydh.nhs.uk/, http://0.0.0.0, docs/worklogs/'
